# GitHub Sponsors (primary funding)
github: [onokumus]

# Community support platforms (optional - uncomment to enable)
# patreon: username
# open_collective: username
# ko_fi: username
# buy_me_a_coffee: username
# liberapay: username
